Add videos
theupdateframework/theupdateframework.io pull request #35
Opened 2022-01-27 18:33 UTC by mnm678

2022-01-27 18:58 UTC, trishankatdatadog approved these changes

2022-01-28 11:13 UTC, joshuagl approved these changes

2022-01-28 11:14 UTC, joshuagl requested changes
Thanks @mnm678 . Minor nit on capitalisation of The Update Framework.

2022-01-28 11:14 UTC, joshuagl commented on content/videos.md
> +## Securing Content Repositories with the Update Framework (TUF)
```suggestion
## Securing Content Repositories with The Update Framework (TUF)
```

2022-01-28 15:03 UTC, mnm678 commented
Thanks @joshuagl, I added your suggestion

2022-01-28 16:20 UTC, merged